### ISSUE TITLE
fix or improve data previews

### ISSUE THREAD

**Issue by Kyle-Falconer** [vta/Open-Data-Portal#20]
sometimes, when a resource is uploaded to a dataset, the preview fails to load.

This may be related to the DataStore not functioning properly.

**Comment by Kyle-Falconer** [comment]
might be fixed when  #10 is completed

**Comment by 3vivekb** [comment]
I found it written somewhere that resource previews will work consistently when data is stored in the  Datastore.  Since I have gotten that working it data previews have been working fine.
