### ISSUE TITLE
Create UI-enabled data portal

### ISSUE THREAD

**Issue by Kyle-Falconer** [vta/Open-Data-Portal#24]
This is a task relating to uploading datasets to the portal.

this is dependent on the portal being deployed to production (issue #9)

**Comment by mthong** [comment]
User story: 
**As a** contributor, 
**I want*** to upload datasets to the data portal via the UI 
**so that** I can populate the portal with new relevant datasets.

**Comment by Kyle-Falconer** [comment]
This is built into CKAN, and partly a duplicate of some of the other issues relating to design and UI/UX, like #1
