### ISSUE TITLE
Create data edit feature

### ISSUE THREAD

**Issue by ghost** [vta/Open-Data-Portal#36]

**Comment by mthong** [comment]
As a contributor, I can edit previously uploaded data to the data portal.

**Comment by Kyle-Falconer** [comment]
What exactly is meant by "edit"?

If it's replacing the data that's previously been uploaded, then that will be doable through the data upload tool.

If it's appending data that's previously been uploaded, then that will be doable through the data append tool (which may be integrated to the upload tool).

**Comment by 3vivekb** [comment]
Appending may be a Data Portal possibility with the python api, but not a requirement.  Editing the data that is on the data portal directly should not be possible.
