### ISSUE TITLE
Refresh SOLR without rebuilding

### ISSUE THREAD

**Issue by 3vivekb** [vta/Open-Data-Portal#58]
Figure out how to refresh the solr index without just rebuilding all of the solr dockerfile.

**Comment by 3vivekb** [comment]
login to the ckan instance:
```
docker exec -i -t ckan /bin/bash
```
and then run this command:
```
paster --plugin=ckan search-index rebuild --config=/etc/ckan/default/production.ini
```

documented here:
[http://docs.ckan.org/en/latest/maintaining/paster.html](http://docs.ckan.org/en/latest/maintaining/paster.html)

**Comment by riordan** [comment]
This can also be done without needing to log into the bash environment:
`docker exec -t ckan paster --plugin=ckan search-index rebuild --config=/etc/ckan/default/production.ini`
