### ISSUE TITLE
Deploy to Production

### ISSUE THREAD

**Issue by Kyle-Falconer** [vta/Open-Data-Portal#9]
Provided we go with Azure, deploy this to Azure using the agreed upon method.

**Comment by Kyle-Falconer** [comment]
still pending platform selection/purchase.

**Comment by Kyle-Falconer** [comment]
Have committed to AWS for the platform.

Still need to move the Elastic IP over to point to the new production deployment.

**Comment by 3vivekb** [comment]
The current deployment, data2.vta.org is considered production.  When we are ready we can move the production over to data.vta.org.
